SELECT ESTADO, LIMITE_DE_CREDITO FROM tabla_de_clientes;

SELECT ESTADO, SUM(LIMITE_DE_CREDITO) AS LIMITE_TOTAL FROM tabla_de_clientes GROUP BY ESTADO;

SELECT ENVASE, MAX(PRECIO_DE_LISTA) AS MAYOR_PRECIO FROM tabla_de_productos GROUP BY ENVASE;

SELECT ENVASE, COUNT(*) FROM tabla_de_productos GROUP BY ENVASE;

SELECT BARRIO, SUM(LIMITE_DE_CREDITO) AS LIMITE FROM tabla_de_clientes GROUP BY BARRIO;

SELECT BARRIO, SUM(LIMITE_DE_CREDITO) AS LIMITE FROM tabla_de_clientes WHERE CIUDAD = 'ciudad de mexico' GROUP BY BARRIO;

SELECT CIUDAD, BARRIO, SUM(LIMITE_DE_CREDITO) AS LIMITE FROM tabla_de_clientes WHERE CIUDAD = 'ciudad de mexico' GROUP BY BARRIO;

SELECT CIUDAD, BARRIO, SUM(LIMITE_DE_CREDITO) AS LIMITE FROM tabla_de_clientes WHERE CIUDAD = 'guadalajara' GROUP BY BARRIO;

SELECT CIUDAD, BARRIO, MAX(LIMITE_DE_CREDITO) AS LIMITE FROM tabla_de_clientes GROUP BY CIUDAD, BARRIO;

SELECT ESTADO, BARRIO, EDAD, MAX(LIMITE_DE_CREDITO) AS LIMITE FROM tabla_de_clientes WHERE EDAD >=20 GROUP BY ESTADO, BARRIO, EDAD ORDER BY EDAD DESC;